# Workflow that performs daily builds of k8snetworkplumbingwg/sriov-network-operator
# The images are based on CentOS 8, CentOS Stream 9, Fedora and Red Hat UBI

name: Multi-arch and multi-distro build for sriov-network-* container images
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:
    strategy:
      matrix:
        container: [ operator, config-daemon, webhook ]
        distro-name: [ centos-stream ]
        distro-version: [ 9 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository for the Dockerfiles
        uses: actions/checkout@v2

      - name: Checkout k8snetworkplumbingwg/sriov-network-operator for the code
        uses: actions/checkout@v2
        with:
          repository: k8snetworkplumbingwg/sriov-network-operator
          path: sriov-network-operator

      - name: Build the ${{ matrix.container }} image for ${{ matrix.distro-name }}-${{ matrix.distro-version }}
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: sriov-network-${{ matrix.container }}
          tags: "${{ matrix.distro-name }}-${{ matrix.distro-version }}"
          containerfiles: |
            ./${{ matrix.distro-name }}/${{ matrix.distro-version }}/Dockerfile.${{ matrix.container }}
          context: sriov-network-operator

      - name: Push the ${{ matrix.container }} image for ${{ matrix.distro-name }}-${{ matrix.distro-version }} to Quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sriov-network-${{ matrix.container }}
          tags: "${{ matrix.distro-name }}-${{ matrix.distro-version }}"
          registry: quay.io/rh-ecosystem-edge
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
